# Generated by Django 3.2.7 on 2021-09-30 10:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image2',
            field=models.CharField(default=datetime.datetime(2021, 9, 30, 10, 55, 37, 328715, tzinfo=utc), max_length=1000000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='image3',
            field=models.CharField(default=datetime.datetime(2021, 9, 30, 10, 55, 54, 900942, tzinfo=utc), max_length=1000000),
            preserve_default=False,
        ),
    ]
