# Generated by Django 3.2.7 on 2021-10-04 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210930_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='images',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
