# Generated by Django 3.2.7 on 2021-10-04 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_postimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
