# Generated by Django 3.2.7 on 2021-10-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_postimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='images',
        ),
        migrations.AlterField(
            model_name='postimage',
            name='images',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
